meta_product_name: "Product Name"
meta_title: "Rooker, the best app to find top junior devs in just seconds, easy and fun !"
meta_description: "This app will help recruiters to find the best junior devs out there very quickly and efficiently"
meta_image: "cover.png"
twitter_account: "@product_twitter_account"
